pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                withEnv(["HOME=${env.WORKSPACE}"]) {

                    sh 'python -m pip install -r requirements.txt'
                    sh 'python -m py_compile manage.py'

                }
            }
        }
        stage('Migrate') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python manage.py makemigrations'
                    sh 'python manage.py migrate'
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python manage.py test'
                }
            }
        }

        stage('Metric I -> Coverage') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install coverage'
                    sh 'python -m coverage run manage.py test'
                    sh 'python -m coverage report --fail-under=70'
                }
            }
        }
        
        stage('Metric II -> pylint') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'pip install pylint'
                    sh 'pip install pylint-django'
                    sh 'python -m pylint StudyBuddy'
                }
            }
        }
    }
    post {
		failure{
			mail to: 'ariefi@ac.sce.ac.il',
			subject: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		success{
			mail to: 'ariefi@ac.sce.ac.il',
			subject: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		always{
			deleteDir()
		}
	}
}
