pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh 'pwd'
                sh 'python -m py_compile BS_PM2021_TEAM_2/manage.py'
            }
        }
    }
}