pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh 'ls'
                sh 'pwd'
                sh 'python -m pip install  --upgrade pip --user'
                sh 'python -m pip install -r requirements.txt'
                sh 'python -m py_compile manage.py'
            }
        }
    }
}