# Generated by Django 3.1.7 on 2021-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='grade')),
                ('birth_date', models.DateField(blank=True, verbose_name='Birth Date')),
                ('personID', models.IntegerField(default=None)),
                ('personalPhone', models.CharField(blank=True, max_length=10, verbose_name='Personal Phone')),
                ('parentName_M', models.CharField(max_length=20, verbose_name='mother name')),
                ('parentPhone_M', models.CharField(max_length=10, verbose_name='mother phone')),
                ('parentName_F', models.CharField(blank=True, max_length=20, verbose_name='father name')),
                ('parentPhone_F', models.CharField(blank=True, max_length=10, verbose_name='father phone')),
                ('theme', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('subjects', models.CharField(max_length=80, verbose_name='subjects')),
                ('theme', models.IntegerField(default=0)),
            ],
        ),
    ]
