# Generated by Django 3.1.7 on 2021-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBuddy', '0002_auto_20210411_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Theme',
            field=models.IntegerField(default=0),
        ),
    ]
